stages:

  initialize_manifest:
    foreach: ${languages}
    do:
      cmd: python initialize_manifest.py
            --lang     ${key}
            --metadata ${item.metadata}
            --wav-dir  ${item.wav_dir}
            --out      data/manifests/${key}/clean.jsonl
      deps:
        - initialize_manifest.py
        - ${item.metadata}
        - ${item.wav_dir}
      params:
        - languages
      outs:
        - data/manifests/${key}/clean.jsonl

  make_manifest:
    foreach: ${languages}
    do:
      cmd: python add_noise_stage.py
            --lang     ${key}
            --manifest data/manifests/${key}/clean.jsonl
            --out-dir  data/manifests/${key}/noisy/
            --noisy-wav-dir data/noisy/${key}/
      deps:
        - make_manifest.py
        - add_noise_stage.py
        - data/manifests/${key}/clean.jsonl
      params:
        - languages
        - snr_levels
        - seed
      outs:
        - data/manifests/${key}/noisy/
        - data/noisy/${key}/
